// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{
  vec3 ka, kd, ks;
  float p;
  vec3 v = -normalize(view_pos_fs_in.xyz);
  float theta = animation_seconds*((2*M_PI)/4);
  vec4 l_p = view*vec4(10*cos(theta), 5.0, 10*sin(theta), 1.0);
  vec3 l = normalize((l_p-view_pos_fs_in).xyz);
  float kd_noise = (perlin_noise(4.24*sphere_fs_in+2.2*sphere_fs_in*sphere_fs_in)+4.2*perlin_noise(sin(0.5*M_PI)*sphere_fs_in))*0.5;
  float ks_noise = sin(0.5*M_PI*perlin_noise(17*sphere_fs_in));
  if(is_moon){
	ka = vec3(0.90, 0.90, 0.90);
	
	kd = clamp(vec3(0.7, 0.7, 0.7)+kd_noise, 0.0, 1.0);
	ks = clamp(vec3(0.2,0.2,0.2)+ks_noise, 0.0 ,1.0);
	p = 200.0;
  }else{
	ka = vec3(0.215686,0.494118,0.721569);
	kd = clamp(vec3(0.2,0.3,0.721569)+kd_noise, 0.0, 1.0);
	ks = clamp(vec3(0.3,0.3,0.3)+ks_noise, 0.0, 1.0);
	p = 500.0;
  }
  color = blinn_phong(ka, kd, ks, p, normalize(normal_fs_in), v, l);
}
